import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
   variable: '--font-geist-sans',
   subsets: ['latin']
});

const geistMono = Geist_Mono({
   variable: '--font-geist-mono',
   subsets: ['latin']
});

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app'
};

export default function RootLayout({
   children
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
         <body className="min-h-screen bg-gradient-to-r from-slate-900 via-sky-900
               to-sky-800  mt-28 text-white">
              <main className="mx-auto  px-5 ">
               {children}

    </main>
         </body>
      </html>
   );
}
