import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
   variable: '--font-geist-sans',
   subsets: ['latin']
});

const geistMono = Geist_Mono({
   variable: '--font-geist-mono',
   subsets: ['latin']
});

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app'
};

export default function RootLayout({
   children
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
         <body className="min-h-screen bg-slate-950 pt-28 text-white">
            <div
               aria-hidden="true"
               className="fixed inset-0 z-0 bg-[linear-gradient(135deg,#0f172b_0%,#024a70_52%,#005986_100%)]"
            />
            <main className="relative z-10 mx-auto px-5">
               {children}
            </main>
         </body>
      </html>
   );
}
